# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameters.ui'
#
# Created: Fri Jun 24 23:02:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(763, 454)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.sig_a = QtGui.QRadioButton(self.groupBox_2)
        self.sig_a.setChecked(True)
        self.sig_a.setObjectName("sig_a")
        self.verticalLayout_3.addWidget(self.sig_a)
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.p_sig_a = QtGui.QLineEdit(self.widget)
        self.p_sig_a.setObjectName("p_sig_a")
        self.verticalLayout_4.addWidget(self.p_sig_a)
        self.verticalLayout_3.addWidget(self.widget)
        self.sig_b = QtGui.QRadioButton(self.groupBox_2)
        self.sig_b.setObjectName("sig_b")
        self.verticalLayout_3.addWidget(self.sig_b)
        self.widget_2 = QtGui.QWidget(self.groupBox_2)
        self.widget_2.setEnabled(False)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.p_sig_b = QtGui.QLineEdit(self.widget_2)
        self.p_sig_b.setObjectName("p_sig_b")
        self.verticalLayout_5.addWidget(self.p_sig_b)
        self.label_3 = QtGui.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.bin_size_edit = QtGui.QLineEdit(self.widget_2)
        self.bin_size_edit.setObjectName("bin_size_edit")
        self.verticalLayout_5.addWidget(self.bin_size_edit)
        self.verticalLayout_3.addWidget(self.widget_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.sig_run = QtGui.QPushButton(self.groupBox_2)
        self.sig_run.setObjectName("sig_run")
        self.horizontalLayout_3.addWidget(self.sig_run)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.linkage_combo = QtGui.QComboBox(self.groupBox_3)
        self.linkage_combo.setObjectName("linkage_combo")
        self.linkage_combo.addItem("")
        self.linkage_combo.addItem("")
        self.linkage_combo.addItem("")
        self.linkage_combo.addItem("")
        self.verticalLayout_6.addWidget(self.linkage_combo)
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.distance_edit = QtGui.QLineEdit(self.groupBox_3)
        self.distance_edit.setObjectName("distance_edit")
        self.verticalLayout_6.addWidget(self.distance_edit)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.cluster_run = QtGui.QPushButton(self.groupBox_3)
        self.cluster_run.setEnabled(False)
        self.cluster_run.setObjectName("cluster_run")
        self.horizontalLayout_4.addWidget(self.cluster_run)
        self.clust_run_all = QtGui.QPushButton(self.groupBox_3)
        self.clust_run_all.setObjectName("clust_run_all")
        self.horizontalLayout_4.addWidget(self.clust_run_all)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.go_db_path = QtGui.QLineEdit(self.groupBox)
        self.go_db_path.setObjectName("go_db_path")
        self.horizontalLayout.addWidget(self.go_db_path)
        self.go_browse = QtGui.QPushButton(self.groupBox)
        self.go_browse.setObjectName("go_browse")
        self.horizontalLayout.addWidget(self.go_browse)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ass_path = QtGui.QLineEdit(self.groupBox)
        self.ass_path.setObjectName("ass_path")
        self.horizontalLayout_6.addWidget(self.ass_path)
        self.ass_browse = QtGui.QPushButton(self.groupBox)
        self.ass_browse.setObjectName("ass_browse")
        self.horizontalLayout_6.addWidget(self.ass_browse)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.p_value_go_edit = QtGui.QLineEdit(self.groupBox)
        self.p_value_go_edit.setObjectName("p_value_go_edit")
        self.verticalLayout_7.addWidget(self.p_value_go_edit)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.go_combo = QtGui.QComboBox(self.groupBox)
        self.go_combo.setObjectName("go_combo")
        self.go_combo.addItem("")
        self.go_combo.addItem("")
        self.go_combo.addItem("")
        self.verticalLayout_7.addWidget(self.go_combo)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.go_run = QtGui.QPushButton(self.groupBox)
        self.go_run.setEnabled(False)
        self.go_run.setObjectName("go_run")
        self.horizontalLayout_5.addWidget(self.go_run)
        self.go_run_all = QtGui.QPushButton(self.groupBox)
        self.go_run_all.setObjectName("go_run_all")
        self.horizontalLayout_5.addWidget(self.go_run_all)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.sig_a, QtCore.SIGNAL("toggled(bool)"), self.widget_2.setDisabled)
        QtCore.QObject.connect(self.sig_b, QtCore.SIGNAL("toggled(bool)"), self.widget.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Significantie", None, QtGui.QApplication.UnicodeUTF8))
        self.sig_a.setText(QtGui.QApplication.translate("Form", "Significance A", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "P-waarde", None, QtGui.QApplication.UnicodeUTF8))
        self.p_sig_a.setText(QtGui.QApplication.translate("Form", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.sig_b.setText(QtGui.QApplication.translate("Form", "Significance B", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "P-waarde", None, QtGui.QApplication.UnicodeUTF8))
        self.p_sig_b.setText(QtGui.QApplication.translate("Form", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Bin grootte", None, QtGui.QApplication.UnicodeUTF8))
        self.bin_size_edit.setText(QtGui.QApplication.translate("Form", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.sig_run.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Clusters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Linkage", None, QtGui.QApplication.UnicodeUTF8))
        self.linkage_combo.setItemText(0, QtGui.QApplication.translate("Form", "average", None, QtGui.QApplication.UnicodeUTF8))
        self.linkage_combo.setItemText(1, QtGui.QApplication.translate("Form", "single", None, QtGui.QApplication.UnicodeUTF8))
        self.linkage_combo.setItemText(2, QtGui.QApplication.translate("Form", "complete", None, QtGui.QApplication.UnicodeUTF8))
        self.linkage_combo.setItemText(3, QtGui.QApplication.translate("Form", "centroid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Treshold", None, QtGui.QApplication.UnicodeUTF8))
        self.distance_edit.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cluster_run.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.clust_run_all.setText(QtGui.QApplication.translate("Form", "Run tot hier", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "GO Enrichment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.go_browse.setText(QtGui.QApplication.translate("Form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Associations", None, QtGui.QApplication.UnicodeUTF8))
        self.ass_browse.setText(QtGui.QApplication.translate("Form", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "P-waarde", None, QtGui.QApplication.UnicodeUTF8))
        self.p_value_go_edit.setText(QtGui.QApplication.translate("Form", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Ontology", None, QtGui.QApplication.UnicodeUTF8))
        self.go_combo.setItemText(0, QtGui.QApplication.translate("Form", "Molecular function", None, QtGui.QApplication.UnicodeUTF8))
        self.go_combo.setItemText(1, QtGui.QApplication.translate("Form", "Biological process", None, QtGui.QApplication.UnicodeUTF8))
        self.go_combo.setItemText(2, QtGui.QApplication.translate("Form", "Cellular component", None, QtGui.QApplication.UnicodeUTF8))
        self.go_run.setText(QtGui.QApplication.translate("Form", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.go_run_all.setText(QtGui.QApplication.translate("Form", "Run tot hier", None, QtGui.QApplication.UnicodeUTF8))

